# Generated by Django 4.2.4 on 2023-08-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['is_complete']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='complete',
            new_name='is_complete',
        ),
    ]
